### ISSUE TITLE
NPM missing latest release

### ISSUE THREAD

**Issue by johnmuhl** [electron-userland/electron-prebuilt#111]
Looks like something went wrong publishing 0.37.3 to NPM. Are there any interesting logs?

**Comment by devlo** [comment]
@maxogden 

Any update on this issue?

**Comment by maxogden** [comment]
@johnmuhl here are the logs, I think

```
2016-03-27T04:51:20.846930+00:00 app[web.1]: npm ERR! fetch failed https://api.github.com/repos/electron-userland/electron-prebuilt/tarball/v0.37.3
2016-03-27T04:51:20.763218+00:00 app[web.1]:      'path-exists': '^1.0.0',
2016-03-27T04:51:20.763220+00:00 app[web.1]:      tarball: 'http://registry.npmjs.org/electron-prebuilt/-/electron-prebuilt-0.37.2.tgz' } }
2016-03-27T04:51:20.847896+00:00 app[web.1]: npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
2016-03-27T04:51:30.877606+00:00 app[web.1]: npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
2016-03-27T04:51:30.876622+00:00 app[web.1]: npm ERR! fetch failed https://api.github.com/repos/electron-userland/electron-prebuilt/tarball/v0.37.3
2016-03-27T04:52:30.904859+00:00 app[web.1]: npm ERR! fetch failed https://api.github.com/repos/electron-userland/electron-prebuilt/tarball/v0.37.3
2016-03-27T04:52:30.908924+00:00 app[web.1]: Failed to publish package
2016-03-27T04:52:30.909755+00:00 app[web.1]: Unhandled rejection Error: fetch failed with status code 403
2016-03-27T04:52:30.909762+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/npm/node_modules/npm-registry-client/lib/fetch.js:51:14)
2016-03-27T04:52:30.909763+00:00 app[web.1]:     at emitOne (events.js:77:13)
2016-03-27T04:52:30.909763+00:00 app[web.1]:     at Request.emit (events.js:169:7)
2016-03-27T04:52:30.909764+00:00 app[web.1]:     at Request.onRequestResponse (/app/node_modules/npm/node_modules/request/request.js:998:10)
```

ENV vars are:

```
API_KEY: <key>
EMAIL:   <my email>
OWNER:   electron-userland
REPO:    electron-prebuilt
SECRET:  <secret>
TOKEN:   <token>
```

**Comment by maxogden** [comment]
I manually published for now

**Comment by johnmuhl** [comment]
Looks like a sporadic failure. I've opened https://github.com/electron-userland/electron-prebuilt-updater/issues/10 to add a retry handler.
