### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by mariusdarila** [electron-userland/electron-prebuilt#115]
After updating to v`0.37.4` my electron app stopped working: 
> App threw an error when running TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1364:5)
    at /projects/electron-react-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
    at /projects/electron-react-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
    at Array.map (native)
    at OptionManager.resolvePresets (/projects/electron-react-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/projects/electron-react-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/projects/electron-react-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at /projects/electron-react-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
    at /projects/electron-react-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
A JavaScript error occurred in the main process

 It seems that it has a problem with babel-register.

**Comment by ungoldman** [comment]
Hi @mariusdarila. electron-prebuilt is not maintained by the github electron team and is just for downloading the latest prebuilt electron binary.

According to @feross (https://github.com/feross/webtorrent-desktop/pull/298):

> 0.37.4 has a broken Buffer implementation and it seems it is (accidentally) using a pre-release version of Node 6

That may be why it's breaking for you. I'd recommend downgrading to 0.37.3 and filing an issue here:

https://github.com/electron/electron/issues

**Comment by mariusdarila** [comment]
thanks :)
