### ISSUE TITLE
Fail at postinstall with node 6.1.0

### ISSUE THREAD

**Issue by Alphmega** [electron-userland/electron-prebuilt#125]
```
159852 silly postinstall electron-prebuilt@0.37.8 D:\Project\angular2-seed-advanced\node_modules\.staging\electron-prebuilt-fb322f77
159853 info lifecycle electron-prebuilt@0.37.8~postinstall: electron-prebuilt@0.37.8
159854 verbose lifecycle electron-prebuilt@0.37.8~postinstall: unsafe-perm in lifecycle true
159855 verbose lifecycle electron-prebuilt@0.37.8~postinstall: PATH: D:\Program Files\nvm\v6.1.0\node_modules\npm\bin\node-gyp-bin;D:\Project\angular2-seed-advanced\node_modules\electron-prebuilt\node_modules\.bin;D:\Project\angular2-seed-advanced\node_modules\.bin;D:\Program Files\NodeJs;D:\Program Files\gradle\bin;D:\Program Files\NodeJS;D:\PROGRA~1\nvm;D:\Program Files\Git;D:\Program Files\Git\bin;C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS\System32\Wbem;D:\Program Files\Php;D:\Program Files\Ruby\bin;D:\Program Files\Android-SDK\platform-tools;D:\Program Files\Android-SDK\tools;D:\Program Files\Python;D:\Program Files\Java\bin;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Program Files\cmder;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\MySQL\MySQL Server 5.6\bin;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;D:\Desktop;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.2 & MySQL Utilities 1.5.2 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.2 & MySQL Utilities 1.5.2 1.5\Doctrine extensions for PHP\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\ProgramData\chocolatey\bin;C:\Users\Administrator\AppData\Local\atom\bin
159856 verbose lifecycle electron-prebuilt@0.37.8~postinstall: CWD: D:\Project\angular2-seed-advanced\node_modules\electron-prebuilt
159857 silly lifecycle electron-prebuilt@0.37.8~postinstall: Args: [ '/d /s /c', 'node install.js' ]
159858 silly lifecycle electron-prebuilt@0.37.8~postinstall: Returned: code: 1  signal: null
159859 info lifecycle electron-prebuilt@0.37.8~postinstall: Failed to exec postinstall script
159860 verbose unlock done using D:\Program Files\NodeJS\npm_cache\_locks\staging-9c47bb7673bc240b.lock for D:\Project\angular2-seed-advanced\node_modules\.staging
159861 silly rollbackFailedOptional Starting
159862 silly rollbackFailedOptional Finishing
159863 silly runTopLevelLifecycles Starting
159864 silly runTopLevelLifecycles Finishing
159865 silly install printInstalled
159866 warn optional Skipping failed optional dependency /chokidar/fsevents:
159867 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.12
159868 verbose stack Error: electron-prebuilt@0.37.8 postinstall: `node install.js`
159868 verbose stack Exit status 1
159868 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nvm\v6.1.0\node_modules\npm\lib\utils\lifecycle.js:239:16)
159868 verbose stack     at emitTwo (events.js:106:13)
159868 verbose stack     at EventEmitter.emit (events.js:191:7)
159868 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nvm\v6.1.0\node_modules\npm\lib\utils\spawn.js:24:14)
159868 verbose stack     at emitTwo (events.js:106:13)
159868 verbose stack     at ChildProcess.emit (events.js:191:7)
159868 verbose stack     at maybeClose (internal/child_process.js:850:16)
159868 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
159869 verbose pkgid electron-prebuilt@0.37.8
159870 verbose cwd D:\Project\angular2-seed-advanced
159871 error Windows_NT 10.0.10586
159872 error argv "D:\\Program Files\\NodeJs\\node.exe" "D:\\Program Files\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install"
159873 error node v6.1.0
159874 error npm  v3.8.6
159875 error code ELIFECYCLE
159876 error electron-prebuilt@0.37.8 postinstall: `node install.js`
159876 error Exit status 1
159877 error Failed at the electron-prebuilt@0.37.8 postinstall script 'node install.js'.
159877 error Make sure you have the latest version of node.js and npm installed.
159877 error If you do, this is most likely a problem with the electron-prebuilt package,
159877 error not with npm itself.
159877 error Tell the author that this fails on your system:
159877 error     node install.js
159877 error You can get information on how to open an issue for this project with:
159877 error     npm bugs electron-prebuilt
159877 error Or if that isn't available, you can get their info via:
159877 error     npm owner ls electron-prebuilt
159877 error There is likely additional logging output above.
159878 verbose exit [ 1, true ]
```

**Comment by TeodorKolev** [comment]
same

**Comment by gopikrishnaA** [comment]
Same issue which I was facing on windows

**Comment by zeke** [comment]
Are you seeing this issue with newer versions of Electron and Node?
