### ISSUE TITLE
Error: electron-prebuilt@1.2.2 postinstall: `node install.js`

### ISSUE THREAD

**Issue by romaincointepas** [electron-userland/electron-prebuilt#151]
npm-debug.log:

```
27294 verbose stack Error: electron-prebuilt@1.2.2 postinstall: `node install.js`
27294 verbose stack Exit status 1
27294 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
27294 verbose stack     at emitTwo (events.js:106:13)
27294 verbose stack     at EventEmitter.emit (events.js:191:7)
27294 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
27294 verbose stack     at emitTwo (events.js:106:13)
27294 verbose stack     at ChildProcess.emit (events.js:191:7)
27294 verbose stack     at maybeClose (internal/child_process.js:852:16)
27294 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
27295 verbose pkgid electron-prebuilt@1.2.2
27296 verbose cwd /Users/romain/testapp/app
27297 error Darwin 15.5.0
27298 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
27299 error node v6.2.1
27300 error npm  v3.9.3
27301 error code ELIFECYCLE
27302 error electron-prebuilt@1.2.2 postinstall: `node install.js`
27302 error Exit status 1
27303 error Failed at the electron-prebuilt@1.2.2 postinstall script 'node install.js'.
27303 error Make sure you have the latest version of node.js and npm installed.
27303 error If you do, this is most likely a problem with the electron-prebuilt package,
27303 error not with npm itself.
27303 error Tell the author that this fails on your system:
27303 error     node install.js
27303 error You can get information on how to open an issue for this project with:
27303 error     npm bugs electron-prebuilt
27303 error Or if that isn't available, you can get their info via:
27303 error     npm owner ls electron-prebuilt
27303 error There is likely additional logging output above.
27304 verbose exit [ 1, true ]
```

**Comment by akashdeepshah** [comment]
Did you find the solution??

**Comment by warka0** [comment]
I would know too.

**Comment by klappy** [comment]
@akashdeepshah and @warka0: 
Following the instructions here addressed it for me: https://github.com/electron-userland/electron-prebuilt/issues/69#issuecomment-164636460

In particular:
`rm -rf ~/.electron/`
`npm clear cache`
`sudo npm install -g electron`

**Comment by semanino** [comment]
The problem is in package electron-download
file `build/cli.js` uses the deprecated `node` command instead of `nodejs` in its first line which reads `#!/usr/bin/env node`

Choose your favourite solution:
- change the file's first line to read `#!/usr/bin/env nodejs`
- or install a compatibility package in your Linux (on Ubuntu 16.04 LTS this is nodejs-legacy so you would run shell command `sudo apt install nodejs-legacy`)
- or create a symlink named `node` to the `nodejs` executable: use e.g. `which nodejs` to find out where it is; if this returns e.g. `/usr/bin/nodejs`, create the symlink with `sudo ln -s /usr/bin/nodejs /usr/bin/node`

**Comment by soyva3** [comment]
Check this out.

https://github.com/electron/electron/issues/10604#issuecomment-333368230
