### ISSUE TITLE
Linux: Can't start electron with /usr/bin/electron script. spawn is broken (path.txt, download via install.js)

### ISSUE THREAD

**Issue by cookiengineer** [electron-userland/electron-prebuilt#154]
Reproduction:

```bash
sudo npm install -g electron-prebuilt;
```

**Problem**:

```bash
electron;
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/lib/node_modules/electron-prebuilt/dist/electron
 ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:449:3
```

**Debugging**:

```bash
which electron;
/usr/bin/electron

cat /usr/lib/node_modules/electron-prebuilt/path.txt;
dist/electron
```

```bash
cd /usr/lib/node_modules/electron-prebuilt;

cat path.txt;
dist/electron

# This works without issues
./dist/electron;
/usr/lib/node_modules/electron-prebuilt/dist/electron;
# This works without issues
```

What is the problem here? How can I fix it?

**Comment by zeke** [comment]
A few questions:

What happens if you install the package locally? e.g.

```
mkdir test
cd test
npm init --yes
npm install electron-prebuilt
./node_modules/.bin/electron
```

Alternatively, what happens if you try to install globally without sudo?

**Comment by zing321** [comment]
Did a `npm update` updated 1.3.5 to 1.3.6 then tried to run `electron .` as I usually do and got this same error. 

```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'E:\apps\animus_client\node_modules\electron-prebuilt\path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (E:\apps\animus_client\node_modules\electron-prebuilt\index.js:4:42)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
```

**Comment by zing321** [comment]
It works after uninstalling the package and installing again.

**Comment by zeke** [comment]
Gonna close this out. Let us know if the problem persists.
