### ISSUE TITLE
Cannot find module './lib/_stream_readable.js'

### ISSUE THREAD

**Issue by HR** [electron-userland/electron-prebuilt#166]
I'm getting the following error when I try to npm update my electron
```bash
> electron-prebuilt@1.2.8 postinstall /Users/HR/GitHub/Project/node_modules/electron-prebuilt
> node install.js

module.js:440
    throw err;
    ^

Error: Cannot find module './lib/_stream_readable.js'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/HR/GitHub/Project/node_modules/concat-stream/node_modules/readable-stream/readable.js:6:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
npm WARN eslint-config-standard@5.3.1 requires a peer of eslint@^2.0.0-rc.0 but none was installed.
npm WARN eslint-config-standard-jsx@1.2.1 requires a peer of eslint@^2.1.0 but none was installed.
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/HR/.nvm/versions/node/v6.1.0/bin/node" "/Users/HR/.nvm/versions/node/v6.1.0/bin/npm" "update"
npm ERR! node v6.1.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@1.2.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.2.8 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.
```

**Comment by zeke** [comment]
This looks like a corrupted npm install issue. Please try `rm -rf node_modules && npm install` and let us know if the problem persists.
