### ISSUE TITLE
electron-prebuilt installation fails on Ubuntu 16.04 LTS 64 bit Intel

### ISSUE THREAD

**Issue by eschen42** [electron-userland/electron-prebuilt#174]
Describe your problem:
I tried running electron-quick-start on Ubuntu 16.04 LTS 64 bit Intel architecture, but the installation failed and prompted me to report the issue. The log is attached per the software's request.

[npm-debug.log.zip](https://github.com/electron-userland/electron-prebuilt/files/392126/npm-debug.log.zip)

The most relevant lines seem to be:

Tell the author that this fails on your system:
     node install.js

**Comment by eschen42** [comment]
After I built and installed
> https://github.com/nodejs/node

I had the node command. It was surprising to learn that I needed to build node, since I had already installed the nodejs package!

Now 'npm install' gives errors like the following:
> `npm ERR! cb is not a function`

and the debug log 
> [npm-debug.log.zip](https://github.com/electron-userland/electron-prebuilt/files/392198/npm-debug.log.zip)

has the following
> `9317 verbose stack TypeError: cb is not a function`
> `9317 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7`
> `9317 verbose stack     at FSReqWrap.oncomplete (fs.js:103:15)`

**Comment by eschen42** [comment]
Apparently, I must have used sudo at some point when I should not have.
When I reverted ownership of files from root to me, I got
`npm install electron-prebuilt`
to work fine for me.

**Comment by eschen42** [comment]
Evidently, Debian now names the executable 'nodejs'; to support electron-prebuilt, it is necessary to 
`sudo apt-get install nodejs-legacy`
to create a symling from 'node' to the true `nodejs` executable.
I found this out by reading
> https://github.com/feross/webtorrent-desktop/issues/633#issuecomment-225332354

and showed that it was true on my own system.
