### ISSUE TITLE
Postinstall cannot find module extract-zip

### ISSUE THREAD

**Issue by rrva** [electron-userland/electron-prebuilt#178]
I currently get this when trying to install electron-prebuilt (a dependency that comes into my project from segmentio/nightmare), when using npm@3.10.3 and node@6.3.1. However, `npm install electron-prebuilt -g` works fine. Also
using npm@3.8.6 and node@v5.12.0 works fine. 

A bug in npm?

Log

```
npm info lifecycle extract-zip@1.5.0~postinstall: extract-zip@1.5.0
npm info lifecycle electron-prebuilt@1.3.2~postinstall: electron-prebuilt@1.3.2

> electron-prebuilt@1.3.2 postinstall /node_modules/electron-prebuilt
> node install.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'extract-zip'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/electron-prebuilt/install.js:9:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
npm info lifecycle electron-prebuilt@1.3.2~postinstall: Failed to exec postinstall script
npm ERR! Linux 4.6.3-040603-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
```

**Comment by rrva** [comment]
The problem was that the application was installed in / and installing it in a separate directory fixed it.

Was totally related to my env, so not a bug, closing.

This fixed it:

https://github.com/rrva/nightmare-752-repro/pull/1/files
