### ISSUE TITLE
NPM Install Issues.

### ISSUE THREAD

**Issue by DevonJWells** [electron-userland/electron-prebuilt#191]
* Electron version: 1.3.6
* Operating system: Windows 8 x64

 I seem to have an unusual issue with the installation. My network is fine. Did a speed test and have 10mbps download and 2mbps up. Bellow is the output:
```
C:\ElecApp>npm install electron --save-dev

> electron@1.3.6 postinstall C:\ElecApp\node_modules\electron
> node install.js

Downloading electron-v1.3.6-win32-x64.zip
Error: read ECONNRESET
C:\ElecApp\node_modules\electron\install.js:22
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1008:11)
    at TLSWrap.onread (net.js:563:26)
npm WARN electest@1.0.0 No repository field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron" "--save-de
"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! electron@1.3.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.3.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ElecApp\npm-debug.log

C:\ElecApp>
````

**Comment by kevinsawicki** [comment]
> Error: read ECONNRESET

This looks like a connection issue.

Are you able to directly download https://github.com/electron/electron/releases/download/v1.3.6/electron-v1.3.6-win32-x64.zip and are you using a proxy?

You may just want to try again since it could have been an availability issue of github.com that was resolved.

**Comment by DevonJWells** [comment]
Thanks. This worked. For some odd issues they were resolved after trying a few hours later.

**Comment by ilogicsoftwares** [comment]
I am Having The same error how can i install https://github.com/electron/electron/releases/download/v1.3.6/electron-v1.3.6-win32-x64.zip manually
