### ISSUE TITLE
Missing `path.txt` on OS X

### ISSUE THREAD

**Issue by kgryte** [electron-userland/electron-prebuilt#193]
After `electron` was updated to `v1.4.1`, my builds started failing on OS X. On Windows and Linux, the builds pass.

* Electron version: `1.4.1`
* Operating system: `OS X 10.9`

```
Error: ENOENT: no such file or directory, open '/Users/travis/build/beep/boop/node_modules/electron/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/Users/travis/build/beep/boop/node_modules/electron/index.js:4:42)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
```

I checked the logs to see whether `electron` installed and found the following stack trace:

```
> electron@1.4.1 postinstall /Users/travis/build/beep/boop/node_modules/electron
> node install.js
... and 1 more
<--- Last few GCs --->
   40849 ms: Mark-sweep 1390.7 (1436.0) -> 1390.7 (1436.0) MB, 2526.4 / 0.0 ms [allocation failure] [scavenge might not succeed].
   43115 ms: Mark-sweep 1390.7 (1436.0) -> 1390.7 (1436.0) MB, 2264.2 / 0.0 ms (+ 1.0 ms in 1 steps since start of marking, biggest step 1.0 ms) [allocation failure] [scavenge might not succeed].
<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
 4: v8::internal::MarkCompactCollector::EvacuateNewSpaceVisitor::AllocateTargetObject(v8::internal::HeapObject*, v8::internal::HeapObject**) [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
 5: v8::internal::MarkCompactCollector::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject*) [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
 6: v8::internal::MarkCompactCollector::VisitLiveObjects(v8::internal::MemoryChunk*, v8::internal::MarkCompactCollector::HeapObjectVisitor*, v8::internal::MarkCompactCollector::IterationMode) [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
 7: v8::internal::MarkCompactCollector::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
 8: v8::internal::PageParallelJob<v8::internal::EvacuationJobTraits>::Task::RunInternal() [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
 9: v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
10: v8::internal::MarkCompactCollector::EvacuateNewSpaceAndCandidates() [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
11: v8::internal::MarkCompactCollector::CollectGarbage() [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
12: v8::internal::Heap::MarkCompact() [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
13: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
14: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, char const*, char const*, v8::GCCallbackFlags) [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
15: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
16: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/travis/.nvm/versions/node/v6.6.0/bin/node]
17: 0x31e610b079a7
```
I checked the install process on both Windows and Linux builds and found that `electron` did install.

This problem persists across all Node.js versions on OS X.

**Comment by kgryte** [comment]
__Update__: I attempted to reproduce on a local machine running OS X 10.10.5. Was able to install `electron`. Not certain the difference or what may have changed in `electron v1.4.1` to cause install issues.

**Comment by kevinsawicki** [comment]
> Allocation failed - JavaScript heap out of memory

@kgryte hmm, I've seen this on Travis CI mac workers as well, I think it might be related to the download progress bar displayed.

Can you see if running `npm install` with `--silent` and see if it fixes it for you?

`electron-prebuilt` uses `electron-download` which uses `nugget` which uses `single-line-log` so it might take some unraveling to find out where this is occurring. There is a quiet option to `electron-download` though which `electron-prebuilt` sets when the npm log level is `silent`.

**Comment by zeke** [comment]
🔍

**Comment by kgryte** [comment]
@kevinsawicki I pinned the version of `electron` to `1.4.0` and that resolved the failure of `electron` to install on OS X on Travis CI. In which case, seems like a regression was introduced with `1.4.1`.

I have yet to try installing with `--silent`, although I would like to avoid this as a long term solution.

**Comment by kevinsawicki** [comment]
This should now be fixed via an upgrade to `electron-download` that reinstalling `1.4.1` should pull in.

**Comment by kgryte** [comment]
@kevinsawicki Thanks!
