### ISSUE TITLE
Having problems getting any electron to run

### ISSUE THREAD

**Issue by scottpixvana** [electron-userland/electron-prebuilt#198]
Having many problems with running electron on MacBook Pro with Sierra install.

Had to go through quite a bit in an attempt to get npm to install since it kept claiming no such directory.

> python ./script/start.py

Traceback (most recent call last):
  File "./script/start.py", line 40, in <module>
    sys.exit(main())
  File "./script/start.py", line 34, in main
    subprocess.check_call([electron] + sys.argv[1:])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(_popenargs, *_kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

No /electron/npm-debug.log found

**Comment by zeke** [comment]
Judging by the `python ./script/start.py`, it looks like you may have cloned Electron from source and are trying to run it. Is that right?

To install a precompiled version of Electron for use in your project, do the following:

```sh
mkdir new-project
npm init --yes
npm install electron
````
