### ISSUE TITLE
Electron fails to run if installed with `npm link` packages on Windows

### ISSUE THREAD

**Issue by mateon1** [electron-userland/electron-prebuilt#200]
- Electron version: 1.3.5 and 1.4.2
- Operating system: Windows 10 x64

When electron is run, on both versions an error window pops up saying "A JavaScript error occurred in the main process" including a stack trace.
In 1.4.2 the stack trace is displayed in the console as well:

```
> electron .


App threw an error during load
Error: Cannot find module 'ipfsd-ctl'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\matin\orbit\node_modules\electron-prebuilt\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\matin\orbit\index.js:13:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

`ipfsd-ctl` does exist under `./node_modules`, but it's an NTFS junction created by `npm link`. Apparently, Electron doesn't like that and throws.

---

P.S. I consider this an installation issue, but this might belong to electron/electron. I decided to post here.

**Comment by mateon1** [comment]
Affects Electron `1.4.3` as well.

**Comment by MrBlenny** [comment]
I am also having this issue. Is there any solution?

**Comment by zeke** [comment]
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!
