### ISSUE TITLE
Keeps showing the same error no matter how I install it

### ISSUE THREAD

**Issue by Myrmechrislee** [electron-userland/electron-prebuilt#237]
If you're having an issue _installing_ Electron, this is the place to report it.
bash-3.2$ ./node_modules/.bin/electron .
/Users/Ants/Desktop/myapp.electron/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/' + path.basename(__dirname) + ' and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/Users/Ants/Desktop/myapp.electron/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Ants/Desktop/myapp.electron/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:571:32)
If you're having an issue _using_ Electron, please report it at https://github.com/electron/electron/issues

* Electron version: ^0.12.7
* Operating system: Mac OS

**Comment by zeke** [comment]
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!
