### ISSUE TITLE
OpenBSD as a supportet platform?

### ISSUE THREAD

**Issue by 0x6373** [electron-userland/electron-prebuilt#241]
* Electron version: 1.6.2
* Operating system: OpenBSD

I was trying to get https://github.com/cryptocat/cryptocat running on an OpenBSD system.
After cloning the repository i ran "npm run setup", but this fails while installing electron@1.6.2 with the following error message:

```
> electron@1.6.2 postinstall /store/cryptocat/cryptocat/node_modules/electron
> node install.js

/store/cryptocat/cryptocat/node_modules/electron/install.js:61
      throw new Error('Electron builds are not available on platform: ' + platform)
      ^

Error: Electron builds are not available on platform: openbsd
    at getPlatformPath (/store/cryptocat/cryptocat/node_modules/electron/install.js:61:13)
    at Object.<anonymous> (/store/cryptocat/cryptocat/node_modules/electron/install.js:19:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
npm ERR! OpenBSD 6.1
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
```

What would be needed to add support for OpenBSD as a platform?
Is this something realistically possible?

**Comment by MarshallOfSound** [comment]
See https://github.com/electron/electron/issues/3797 free BSD support, not sure about difference between freebsd and openbsd but I assume it's a similar issue 👍

**Comment by ghost** [comment]
> See [electron/electron#3797](https://github.com/electron/electron/issues/3797) free BSD support, not sure about difference between freebsd and openbsd but I assume it's a similar issue +1

It probably is not. Both are completely different OS and not like Linux distros.
