### ISSUE TITLE
Can't install electron 1.7.1 locally using npm 5

### ISSUE THREAD

**Issue by leo** [electron-userland/electron-prebuilt#258]
When trying to install the "electron" package using npm 5, I get this error:

```
> fsevents@1.1.1 install /......../node_modules/fsevents
> node install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/......../node_modules/fsevents/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@https://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.33.tgz
node-pre-gyp info using node@7.10.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack TypeError: Cannot read property 'version' of null
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/......../node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:270:32)
node-pre-gyp ERR! stack     at install (/......../node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:168:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/......../node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:50:37)
node-pre-gyp ERR! stack     at run (/......../node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/......../node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:571:32)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:580:10)
node-pre-gyp ERR! stack     at Module.load (module.js:488:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:447:12)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:439:3)
node-pre-gyp ERR! System Darwin 16.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/......../node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /......../node_modules/fsevents
node-pre-gyp ERR! node -v v7.10.0
node-pre-gyp ERR! node-pre-gyp -v vhttps://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.33.tgz
node-pre-gyp ERR! not ok 
Cannot read property 'version' of null

> lint-staged@3.5.0 postinstall /......../node_modules/lint-staged
> echo "🚫💩 lint-staged installed! 
Do not forget to configure it. See https://github.com/okonet/lint-staged/blob/master/README.md" && exit 0

🚫💩 lint-staged installed! 
Do not forget to configure it. See https://github.com/okonet/lint-staged/blob/master/README.md

> electron@1.7.1 postinstall /......../node_modules/electron
> node install.js

/......../node_modules/electron/install.js:47
  throw err
  ^

Error: Failed to find Electron vhttps://registry.npmjs.org/electron/ for darwin-x64 at https://github.com/electron/electron/releases/download/vhttps://registry.npmjs.org/electron//electron-vhttps://registry.npmjs.org/electron/-darwin-x64.zip
    at Request.<anonymous> (/......../node_modules/nugget/index.js:169:61)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestResponse (/......../node_modules/request/request.js:1074:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.1.tgz (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.1 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```
* Electron version: 1.7.1
* Operating system: macOS

**Comment by antoinerousseau** [comment]
any update on this?

**Comment by yvele** [comment]
I've opened an issue on **node-pre-gyp** repo https://github.com/mapbox/node-pre-gyp/issues/298

**Comment by cyberhck** [comment]
This started happening for me too, after a while of debugging, it turns out that the version written to package file is different now. At first it used to just list the version as `x.x.x` and now I've got `https://registry.npmjs.org/electron/-/electron-1.6.2.tgz` in my case. So it's trying to download `https://github.com/electron/electron/releases/download/vhttps://registry.npmjs.org/electron//electron-vhttps://registry.npmjs.org/electron/-linux-x64.zip`.

**Comment by maifs** [comment]
I am facing the same issue .
what do i need to fix it ?
Kindly guide. thank you.

https://stackoverflow.com/questions/44462901/how-to-install-latest-angular-cli-using-visual-studio-2017-node-js-interactive-w

**Comment by leo** [comment]
[This](https://github.com/npm/npm/issues/16728) is the problem.

**Comment by zertyz** [comment]
... and how to solve it? I still can't install it. Is the only possibility to downgrade npm?

**Comment by nikhilag** [comment]
What is the solution here?

**Comment by cyberhck** [comment]
@nikhilag for now either you can use older version of npm, or: I thought it's a breaking change and made a pr: #261 , you can use it temporarily. or also, you can change the version which gets written to package.json inside node_modules/electron...

**Comment by Teknologica** [comment]
It seems to be caused by the npm `version`, running `4.1.2` works while using `5.0.4` seems to cause the issue for Mac or Windows.

**Comment by DSBalaban** [comment]
Thought I'd update that the issue persists on Linux using `npm@5.3.0` as well.

**Comment by danilaml** [comment]
So is there any resolution to this (all I've seen is a bunch of workarounds)? Is there a specific issue/bug to track? Is it going to be fixed?
