### ISSUE TITLE
Electron not installing

### ISSUE THREAD

**Issue by AndreAmo** [electron-userland/electron-prebuilt#90]
I'm trying to clone and run electron quick start example and I'm unable to install electron itself

```
> electron-prebuilt@0.36.5 postinstall /Users/iMac Casa/electron-quick-start/node_modules/electron-prebuilt
> node install.js

/Users/iMac Casa/electron-quick-start/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: end of central directory record signature not found
    at /Users/iMac Casa/electron-quick-start/node_modules/yauzl/index.js:167:14
    at /Users/iMac Casa/electron-quick-start/node_modules/yauzl/index.js:473:5
    at /Users/iMac Casa/electron-quick-start/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.36.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.36.5 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/iMac Casa/electron-quick-start/npm-debug.log
```
I've already checked my node and npm version and they're both up to date, I'm also attaching here the debug log
[npm-debug.log.zip](https://github.com/mafintosh/electron-prebuilt/files/102205/npm-debug.log.zip)

**Comment by Artem-Schander** [comment]
same here.
already tried #69 with no success.
```
sh: node: command not found
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "electron-prebuilt" "-g"
npm ERR! node v5.5.0
npm ERR! npm  v3.6.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
```

**Comment by maxogden** [comment]
@AndreAmo that error sounds like the electron zip download failed and the zip got corrupted. you might try again, it could just be a hiccup with your network or with npm

**Comment by AndreAmo** [comment]
The comment at #69 allowed me to install Electron but I think it's still an issue, feel free to close it or to leave it open though

**Comment by AndreAmo** [comment]
I'm not sure whether it was an download error or not but before opening the issue I tried several times in different moments, anyway I just tried the solution in the comment at #69 and the install went through. Thanks for your help

**Comment by ngoldman** [comment]
Resolved!
